apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins/agent: maven-docker
spec:
  containers:
    - name: maven-docker
      image: docker:24.0.7-dind
      command:
        - cat
      tty: true
      volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock
        - name: maven-cache
          mountPath: /root/.m2
    - name: maven
      image: maven:3.9.9-eclipse-temurin-23
      command:
        - cat
      tty: true
      volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock
        - name: maven-cache
          mountPath: /root/.m2
  volumes:
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock
    - name: maven-cache
      emptyDir: {}
