apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins/agent: maven-docker
spec:
  containers:
    - name: maven-docker
      image: maven:3.9.9-eclipse-temurin-23
      tty: true
      command:
        - cat
      securityContext:
        privileged: true  
      volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock
        - name: maven-cache
          mountPath: /root/.m2
      resources:
        requests:
          memory: "2Gi"
          cpu: "1000m"
        limits:
          memory: "4Gi"
          cpu: "2000m"
  volumes:
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock
    - name: maven-cache
      emptyDir: {}
