apiVersion: v1
kind: Pod
metadata:
  name: jenkins-agent-kaniko
  labels:
    jenkins/agent: "true"
spec:
  containers:
    - name: maven
      image: maven:3.9.9-eclipse-temurin-23
      command:
        - cat
      tty: true
    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      args: ["--dockerfile=/workspace/Dockerfile",
             "--context=/workspace",
             "--destination=sarinkejohn/nbc-devops-transaction:latest"]
      volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: dockerhub-secret
