apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins/label: maven-kaniko-agent
spec:
  serviceAccountName: jenkins
  containers:
  - name: jnlp
    image: jenkins/inbound-agent:latest
    args: ['$(JENKINS_SECRET)', '$(JENKINS_NAME)']
    tty: true
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"

  - name: maven
    image: maven:3.9.9-eclipse-temurin-23
    command:
    - cat
    tty: true
    volumeMounts:
    - name: workspace-volume
      mountPath: /workspace
    resources:
      requests:
        memory: "1024Mi"
        cpu: "1"

  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    volumeMounts:
      - name: workspace-volume
        mountPath: /workspace
      - name: kaniko-secret
        mountPath: /kaniko/.docker
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"

  volumes:
    - name: workspace-volume
      emptyDir: {}
    - name: kaniko-secret
      secret:
        secretName: dockerhub-secret
