apiVersion: v1
kind: Pod
metadata:
  name: jenkins-agent-kaniko
  labels:
    jenkins/agent: "true"
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    command:
      - /busybox/sh
      - -c
      - "sleep infinity"
    volumeMounts:
      - name: workspace-volume
        mountPath: /workspace
      - name: kaniko-secret
        mountPath: /kaniko/.docker

