CREATE DATABASE IF NOT EXISTS nbcdb;
USE nbcdb;
CREATE TABLE IF NOT EXISTS transactions (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  service_name VARCHAR(255),
  name VARCHAR(255),
  amount VARCHAR(64),
  account VARCHAR(128),
  reference VARCHAR(255) NOT NULL UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
