apiVersion: v1
kind: Service
metadata:
  name: temenos-fund-transfer-api-service
  namespace: fund-transfer
  labels:
    app: temenos-fund-transfer-api
spec:
  selector:
    app: temenos-fund-transfer-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 8765
  type: NodePort
 