
name: Build and Push Docker Image

on:
  push:
    branches:
      - master
env:
  APP_VERSION: 1.0.0

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 21
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'

      # Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Build the project
      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: |
            sarinkejohn/nbc-devops-webservice:${{ APP_VERSION }}
            sarinkejohn/nbc-devops-webservice:${{ github.sha }}
            sarinkejohn/nbc-devops-webservice:latest
          push: true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Update K8s manifest with new image tag
        run: |
          sed -i -E "s|(image:\s*docker.io/sarinkejohn/nbc-devops-webservice:).*|\1${{ github.run_number }}|" k8s/app/nbc-devops-webservice-deployment.yaml

      - name: Commit and Push updated manifest
        run: |
                git config user.name "github-actions[bot]"
                git config user.email "github-actions[bot]@users.noreply.github.com"
                git add k8s/app/nbc-devops-webservice-deployment.yaml
                git diff-index --quiet HEAD || git commit -m "Update image tag to ${{ github.run_number }}"
                git push
 