name: CI/CD TemenosSpring

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Java
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      # Step 3: Build and test with Maven
      - name: Build and test with Maven
        run: mvn clean install

      # Step 4: Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Step 5: Build and push Docker image
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/springboot-app:${{ github.sha }} .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/springboot-app:${{ github.sha }}
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/springboot-app:${{ github.sha }} ${{ secrets.DOCKER_HUB_USERNAME }}/springboot-app:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/springboot-app:latest